version_settings(constraint='>=0.22.2')

k8s_yaml(['k8s/namespaces.yml'])

docker_build(
    'k8s-tilt-dev-example-node-nestjs-app',
    './apps/node-nestjs-app/',
    target='development',
)

k8s_yaml(['k8s/node-nestjs-app/deployment.yml', 'k8s/node-nestjs-app/service.yml'])

docker_build(
  'k8s-tilt-dev-example-python-fastapi-app',
  './apps/python-fastapi-app/',
  target='development',
)

k8s_yaml(['k8s/python-fastapi-app/deployment.yml', 'k8s/python-fastapi-app/service.yml'])

k8s_yaml('k8s/ingress.yml')
