service: ${env:SERVICE_NAME, 'Middy'}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    useChildProcesses: true
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, env:STAGE, 'local'}
  region: ${opt:region, env:AWS_REGION, 'us-east-1'}
  profile: ${opt:aws-profile, env:AWS_PROFILE, ''}
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  officialMiddlewareExample:
    handler: src/handlers/post.officialMiddlewareHandler
    events:
      - http:
           path: /
           method: POST
