---
service: ${env:SERVICE_NAME}

frameworkVersion: "4"

plugins:
  - serverless-localstack

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true
  include:
    - "!./**"
    - "**/*.py"
  exclude:
    - "**"

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  runtime: python3.12
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${env:S3_LAMBDA_TRIGGER_BUCKET_NAME}
        - arn:aws:s3:::${env:S3_LAMBDA_TRIGGER_BUCKET_NAME}/*
        - arn:aws:s3:::${env:S3_EXTRA_BUCKET_NAME}
        - arn:aws:s3:::${env:S3_EXTRA_BUCKET_NAME}/*

functions:
  slsS3LocalExampleResolver:
    handler: src.handlers.s3.on_object_created.handler
    runtime: python3.12
    events:
      - s3:
          bucket: ${env:S3_LAMBDA_TRIGGER_BUCKET_NAME}
          event: s3:ObjectCreated:*
          # rules:
          #   - prefix: uploads/
          #   - suffix: .jpg

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_EXTRA_BUCKET_NAME}

  Outputs:
    S3BucketNameOutputKey:
      Value: !Ref S3Bucket
