service: ${env:SERVICE_NAME}

frameworkVersion: '4'

plugins:
  - serverless-offline

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 3000
    port: 3000
    noPrependStageInUrl: true

provider:
  name: aws
  stage: local
  runtime: nodejs22.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
