service: ${env:SERVICE_NAME}

frameworkVersion: "4"

useDotenv: true

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!**"
    - ".build/src/resolvers/**"

provider:
  name: aws
  stage: local
  runtime: nodejs24.x
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

functions:
  AppSyncExampleResolver:
    handler: .build/src/resolvers/handler.graphqlHandler

resources:
  Resources:
    GraphQlApi:
      Type: AWS::AppSync::GraphQLApi
      Properties:
        Name: AppSyncExample
        AuthenticationType: API_KEY
        XrayEnabled: false
        Tags:
          - Key: name
            Value: AppSyncExample
    GraphQlSchema:
      Type: AWS::AppSync::GraphQLSchema
      Properties:
        ApiId: !GetAtt GraphQlApi.ApiId
        Definition: ${file(./schema.graphql)}
    GraphQlApiAppSyncExampleapikey:
      Type: AWS::AppSync::ApiKey
      Properties:
        ApiId: !GetAtt GraphQlApi.ApiId
        Description: "NaN AppSync API Key"
        Expires: ${file(./api-key-expiration.js)}
    GraphQlDsAppSyncExamplelambdaDataSourceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AppSync-Datasource-AppSyncExample_lambdaDataSource
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: lambda:InvokeFunction
                  Resource: !GetAtt AppSyncExampleResolverLambdaFunction.Arn
    GraphQlDsAppSyncExamplelambdaDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        ApiId: !GetAtt GraphQlApi.ApiId
        Name: AppSyncExample_lambdaDataSource
        Description: "NaN AppSync Lambda DataSource"
        Type: AWS_LAMBDA
        ServiceRoleArn: !GetAtt GraphQlDsAppSyncExamplelambdaDataSourceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt AppSyncExampleResolverLambdaFunction.Arn
    GraphQlResolverQuerygetResource:
      Type: AWS::AppSync::Resolver
      DependsOn: GraphQlSchema
      Properties:
        ApiId: !GetAtt GraphQlApi.ApiId
        TypeName: Query
        FieldName: getResource
        Kind: UNIT
        DataSourceName: !GetAtt GraphQlDsAppSyncExamplelambdaDataSource.Name
        ResponseMappingTemplate: ${file(./mapping-templates/response.vtl)}
    GraphQlResolverQuerygetResources:
      Type: AWS::AppSync::Resolver
      DependsOn: GraphQlSchema
      Properties:
        ApiId: !GetAtt GraphQlApi.ApiId
        TypeName: Query
        FieldName: getResources
        Kind: UNIT
        DataSourceName: !GetAtt GraphQlDsAppSyncExamplelambdaDataSource.Name
        ResponseMappingTemplate: ${file(./mapping-templates/response.vtl)}
    GraphQlResolverMutationcreateResource:
      Type: AWS::AppSync::Resolver
      DependsOn: GraphQlSchema
      Properties:
        ApiId: !GetAtt GraphQlApi.ApiId
        TypeName: Mutation
        FieldName: createResource
        Kind: UNIT
        DataSourceName: !GetAtt GraphQlDsAppSyncExamplelambdaDataSource.Name
        ResponseMappingTemplate: ${file(./mapping-templates/response.vtl)}
    GraphQlWaf:
      Type: AWS::WAFv2::WebACL
      Properties:
        Description: ACL rules for AppSync AppSyncExample
        Name: ${self:service}-${sls:stage}-node-typescript-appsync-waf
        Scope: REGIONAL
        DefaultAction:
          Allow: {}
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: ${self:service}-${sls:stage}-node-typescript-appsync-waf
          SampledRequestsEnabled: true
        Tags:
          - Key: name
            Value: AppSyncExample
        Rules:
          - Name: Throttle
            Priority: 100
            Action:
              Block: {}
            Statement:
              RateBasedStatement:
                Limit: 200
                AggregateKeyType: IP
            VisibilityConfig:
              CloudWatchMetricsEnabled: true
              MetricName: node-typescript-appsync-throttle
              SampledRequestsEnabled: true
    GraphQlWafAssoc:
      Type: AWS::WAFv2::WebACLAssociation
      Properties:
        ResourceArn: !GetAtt GraphQlApi.Arn
        WebACLArn: !GetAtt GraphQlWaf.Arn
  Outputs:
    AppSyncApiUrl:
      Value: !GetAtt GraphQlApi.GraphQLUrl
