region             = "us-east-1"
name               = "nanlabs"
namespace          = "example-namespace"
environment        = "staging"
vpc_cidr_block     = "10.0.0.0/16"
db_name            = "nanlabsdb"
db_master_username = "nanlabsuser"
