name: Continuous Integration

concurrency:
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

on:
  workflow_dispatch:

  schedule:
    - cron: "31 1,12 * * *"

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  shellcheck:
    name: Shellcheck
    permissions:
      contents: read
    uses: ./.github/workflows/shellcheck.yml

  tf-check:
    name: Terraform Check
    permissions:
      contents: read
    uses: ./.github/workflows/tf-check.yml

  markdownlint:
    name: Markdownlint
    permissions:
      contents: read
    uses: ./.github/workflows/markdownlint.yml

  todo:
    if: github.event_name == 'push'
    name: TODO
    permissions:
      contents: read
      issues: write
    uses: ./.github/workflows/todo.yml

  update-readme:
    if: github.event_name == 'push'
    name: Update README
    permissions:
      contents: write
    uses: ./.github/workflows/generate-readme.yml

  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Pull Request Validation
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/pr-review.yml
