name: Pull Request Validation

concurrency:
  group: pull_request_${{ github.event.number }}
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  pr-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Setup Danger Files
        run: |
          echo "Setting up Danger files..."
          mv tools/danger/* .

      - uses: actions/setup-node@v4
        with:
          node-version: "v24.17.0"

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Danger JS Action
        run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
